name: "Bug Report - Video SEO"
description: "Report a bug for the Yoast SEO plugin"
title: "[Bug]: "
labels: ["status/awaiting_triage"]
body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: "Prerequisites"
      options:
        - label: "I've searched for any related issues and avoided creating a duplicate issue."
          required: true
        - label: "Make sure you are using the most updated versions of Yoast, WordPress & your theme."
          required: false
  - type: markdown
    attributes:
      value: |
        ### Please give us a description of what happened to reproduce the issue
        ###### Steps necessary to reproduce this, including the expected and actual results.
  - type: textarea
    id: reproduction-steps
    validations:
      required: true
    attributes:
      label: "Step-by-step reproduction instructions"
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      value: |
        1.
        2.
        3.
        4.
  - type: textarea
    id: expected-results
    validations:
      required: true
    attributes:
      label: "Expected results"
      placeholder: |
        1.
  - type: textarea
    id: steps_to_reproduce
    validations:
      required: true
    attributes:
      label: "Actual results"
      placeholder: |
        1. 
  - type: markdown
    attributes:
      value: |
        ## Technical info
        ###### If you are using Gutenberg, Elementor or the Classic Editor plugin, please make sure you have updated to the latest version.
  - type: dropdown
    id: affected-editor
    attributes:
      label: "Affected Editors"
      description: If relevant, which editor is affected (or editors)
      multiple: true
      options:
        - Block Editor
        - Gutenberg Editor
        - Elementor Editor
        - Classic Editor 
        - Others
    validations:
      required: true
  - type: input
    id: other_browser
    attributes:
      label: If your using other editor (mention the editor and version)
      placeholder: "Type the name of the editor and version"
    validations:
      required: false
  - type: dropdown
    id: browser_info
    attributes:
      label: "Browser"
      description: If relevant, which editor is affected (or editors)
      multiple: true
      options:
        - Chrome
        - Mozilla
        - Edge
        - Brave
        - Safari
        - Other
    validations:
      required: false
  - type: input
    id: yoast_seo_version
    attributes:
      label: Yoast SEO Version
      placeholder: "Type the version of Yoast SEO"
    validations:
      required: true
  - type: input
    id: wordpress_version
    attributes:
      label: WordPress Version
      placeholder: "Type the version of WordPress"
    validations:
      required: true
