name: "Bug Report - Video SEO"
description: "Create a report to help us improve the Yoast Video SEO plugin"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: "Prerequisites"
      options:
        - label: "I've searched for any related issues and avoided creating a duplicate issue."
          required: true
        - label: "Make sure you are using the most updated versions of Yoast, WordPress & your theme."
          required: false
  - type: markdown
    attributes:
      value: |
        ### Please give us a description of what happened to reproduce the issue
  - type: textarea
    id: reproduction-steps
    validations:
      required: true
    attributes:
      label: "Step-by-step reproduction instructions"
      description: Steps necessary to reproduce this, including the expected and actual results.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      value: |
        1. 
        2. 
        3. 
  - type: textarea
    id: expected-results
    validations:
      required: true
    attributes:
      label: "Expected results"
      placeholder: |
        1.
      value: |
        1. 
  - type: textarea
    id: steps_to_reproduce
    validations:
      required: true
    attributes:
      label: "Actual results"
      placeholder: |
        1. 
      value: |
        1. 
  - type: textarea
    id: screenshots_recording_code_snippet
    validations:
      required: true
    attributes:
      label: "Screenshots, screen recording, code snippet"
      description: If possible, please provide a screenshot, a screen recording or a code snippet which demonstrates the bug.
      placeholder: Attach files by dragging & dropping, selecting or pasting them.
  - type: markdown
    attributes:
      value: |
        ## Technical info
        ###### If you are using Gutenberg, Elementor or the Classic Editor plugin, please make sure you have updated to the latest version.
  - type: dropdown
    id: affected-editor
    attributes:
      label: "Affected Editors"
      description: If relevant, which editor is affected (or editors)
      multiple: true
      options:
        - Block Editor
        - Gutenberg Editor
        - Elementor Editor
        - Classic Editor 
        - Others
    validations:
      required: true
  - type: input
    id: other_browser
    attributes:
      label: If your using other editor (mention the editor and version)
      placeholder: "Type the name of the editor and version"
    validations:
      required: false
  - type: dropdown
    id: browser_info
    attributes:
      label: "Browser (s)"
      description: Select which browser is affected (or browsers)
      multiple: true
      options:
        - Chrome
        - Mozilla
        - Edge
        - Brave
        - Safari
        - Other
    validations:
      required: false
  - type: textarea
    id: used-versions
    validations:
      required: true
    attributes:
      label: "Used Versions"
      placeholder: |
        Device you are using: 
        Operating system: 
        PHP version: 
        WordPress version: 
        WordPress Theme: 
        Yoast SEO version: 
        Yoast SEO Video version: 
        Gutenberg plugin version (if relevant): 
        Elementor plugin version (if relevant): 
        Classic Editor plugin version (if relevant): 
        Relevant plugins in case of a bug: 
      value: |
        Device you are using: 
        Operating system: 
        PHP version: 
        WordPress version: 
        WordPress Theme: 
        Yoast SEO version: 
        Yoast SEO Video version: 
        Gutenberg plugin version (if relevant):  
        Elementor plugin version (if relevant): 
        Classic Editor plugin version (if relevant): 
        Relevant plugins in case of a bug: 
