blank_issues_enabled: false
contact_links:
  - name: Blank Issues
    url: https://github.com/josevarghese/Support/issues/new
    about: Open a blank issue for issues not related to bug or design implementation
